SPOOL project.out
SET ECHO ON

/*
CIS-353 Bus Company Database Team 5
*/

DROP TABLE Rider CASCADE CONSTRAINTS;
DROP TABLE Bus CASCADE CONSTRAINTS;
DROP TABLE Driver CASCADE CONSTRAINTS;
DROP TABLE Route CASCADE CONSTRAINTS;
DROP TABLE Stop CASCADE CONSTRAINTS;
DROP TABLE FinHistory CASCADE CONSTRAINTS;
DROP TABLE SchedArrivalTime CASCADE CONSTRAINTS;
DROP TABLE RodeOn CASCADE CONSTRAINTS;
DROP TABLE AssignedTo CASCADE CONSTRAINTS;
DROP TABLE StopOnRoute CASCADE CONSTRAINTS;


CREATE TABLE Rider 
(
	riderId INTEGER PRIMARY KEY,
	fName VARCHAR(15) NOT NULL,
	lName VARCHAR(15) NOT NULL
);

CREATE TABLE Driver
(
	Ssn INTEGER PRIMARY KEY,
	fName VARCHAR(15) NOT NULL,
	lName VARCHAR(15) NOT NULL,
	salary INTEGER NOT NULL,
	dRank INTEGER NOT NULL,
	startDate DATE NOT NULL
);

CREATE TABLE Bus
(
	VIN INTEGER PRIMARY KEY,
	numSeats INTEGER NOT NULL,
	driverSsn INTEGER NOT NULL,
	CONSTRAINT fKey1 FOREIGN KEY (driverSsn) REFERENCES Driver(Ssn) ON DELETE CASCADE
);

CREATE TABLE Route
(
	rNum INTEGER PRIMARY KEY,
	startLoc VARCHAR(16) NOT NULL,
	endLoc VARCHAR(16) NOT NULL
);

CREATE TABLE Stop
(
	stopName VARCHAR(16) Primary KEY,
	stopCapacity INTEGER NOT NULL
);

CREATE TABLE FinHistory
(
	historyDate DATE,
	routeNum INTEGER,
	CONSTRAINT pKey1 PRIMARY KEY (historyDate, routeNum),
	CONSTRAINT fKey2 FOREIGN KEY (routeNum) REFERENCES Route(rNum)
);

CREATE TABLE SchedArrivalTime
(
	schedArrivalTime VARCHAR(16),
	stopName VARCHAR(16),
	CONSTRAINT pKey2 PRIMARY KEY (schedArrivalTime, stopName),
	CONSTRAINT fKey3 FOREIGN KEY (stopName) REFERENCES Stop(stopName)
);

CREATE TABLE RodeOn
(
	passengerID INTEGER,
	busVin INTEGER,
	CONSTRAINT pKey3 PRIMARY KEY (passengerID, busVin),
	rideDate DATE NOT NULL,
	onStop VARCHAR(16) NOT NULL,
	offStop VARCHAR(16) NOT NULL,
	CONSTRAINT fKey4 FOREIGN KEY (passengerID) REFERENCES Rider(riderId),
	CONSTRAINT fKey5 FOREIGN KEY (busVin) REFERENCES Bus(Vin),
	CONSTRAINT fKey6 FOREIGN KEY (onStop) REFERENCES Stop(stopName),
	CONSTRAINT fKey7 FOREIGN KEY (offStop) REFERENCES Stop(stopName)
);

CREATE TABLE AssignedTo
(
	vIn Integer,
	rNum Integer,
	dAssigned Date NOT NULL,
	dRemoved DATE NOT NULL,
	CONSTRAINT pKey4 PRIMARY KEY (vIn, rNum),
	CONSTRAINT fKey8 FOREIGN KEY (vIn) REFERENCES Bus(VIN),
	CONSTRAINT fKey9 FOREIGN KEY (rNum) REFERENCES Route(rNum)
);

CREATE TABLE StopOnRoute
(
	rNum INTEGER,
	stopName VARCHAR(16),
	stopSequence Integer NOT NULL,
	CONSTRAINT pKey5 PRIMARY KEY (rNum, stopName),
	CONSTRAINT fKey10 FOREIGN KEY (rNum) REFERENCES Route(rNum),
	CONSTRAINT fKey11 FOREIGN KEY (stopName) REFERENCES Stop(stopName)
);	


SET FEEDBACK OFF

INSERT INTO Rider VALUES (123, 'John', 'Smith');
INSERT INTO Driver VALUES (443243, 'Kevin', 'Jones', 45000, 2, TO_DATE('08/09/2012', 'DD/MM/YYYY'));
INSERT INTO Bus VALUES (1234433, 64, 443243);
INSERT INTO Route VALUES (5, '123 W 5th St', 'Monroe Ave');
INSERT INTO Route VALUES (4, 'Monroe Ave', '111 Michigan St');
INSERT INTO Stop VALUES ('123 W 5th St', 25);
INSERT INTO Stop VALUES ('111 Michigan St', 50);
INSERT INTO Stop VALUES ('Monroe Ave', 55);
INSERT INTO finHistory VALUES (TO_DATE('08/09/2014', 'DD/MM/YYYY'), 5);
INSERT INTO SchedArrivalTime VALUES ('09:30pm', 'Monroe Ave');
INSERT INTO RodeOn VALUES (123, 1234433, TO_DATE('08/05/2001', 'DD/MM/YYYY'), 'Monroe Ave', '123 W 5th St');
INSERT INTO AssignedTo VALUES (1234433, 5, TO_DATE('04/04/2001', 'DD/MM/YYYY'), TO_DATE('05/04/2001', 'DD/MM/YYYY'));
INSERT INTO StopOnRoute VALUES(5, 'Monroe Ave', 1);
INSERT INTO StopOnRoute Values(4, 'Monroe Ave', 8);

SET FEEDBACK ON
COMMIT;

SELECT * FROM Rider;
SELECT * FROM Driver;
SELECT * FROM Bus;
SELECT * FROM Route;
SELECT * FROM Stop;
SELECT * FROM finHistory;
SELECT * FROM SchedArrivalTime;
SELECT * FROM RodeOn;
SELECT * FROM AssignedTo;
SELECT * FROM StopOnRoute;

COMMIT;

SPOOL OFF
